#!/bin/bash

# (C) 2022 Henri Shustak
# Licenced under the Apache Licence
# http://www.apache.org/licenses/LICENSE-2.0
# Latest copy of this script is available from : http://www.github.com/henri/install-rosetta2

# About : This script installs rosseta on apple silicon systems.
# This script requires an internet connection to work.


# Note : This script is going to exit with non zero exit value if
#        the system has no internet connection or Apple servers not accessible
#
# Note : This script will not update rosetta just install rosetta, 
#        if not currently installed and running.


# internal variable and system tools
SOFTWAREUPDATE="/usr/sbin/softwareupdate"
PGREP="/usr/bin/pgrep"
ARCH="/usr/bin/arch"

# sometimes rosetta takes a while to start up. 
# How long are we going to wait for it to start before giving up (approximately)
ROSETTA_MAX_WAIT_TIME_SECONDS=120
SECONDS_WAITED=0

# make sure tools are accessible
if [ -f "${SOFTWAREUPDATE}" ] && [ -f "${PGREP}" ] && [ -f "${ARCH}" ] ; then

	# check if we are runing on AMD64 systems (Apple Silicon)
	SYSTEM_ARCH=`"${ARCH}"`
	if [ "${SYSTEM_ARCH}" == "arm64" ] ; then
	
		# check if rosetta has already been installed 
		ROSETTA_INSTALLED=`if ${PGREP} oahd >/dev/null 2>&1 ; then echo "YES"; else echo "NO" ; fi`
	
		if [ "${ROSETTA_INSTALLED}" == "NO" ] ; then
			# attempt to install rosetta 2 
			${SOFTWAREUPDATE} --install-rosetta --agree-to-license >/dev/null 2>&1
			EXIT_VALUE=$?
			if [ "${EXIT_VALUE}" != 0 ] ; then exit ${EXIT_VALUE} ; fi
			
			# seems like rosetta has installed but now we need to wait for it to start up.
			EXIT_VALUE=50
			while [ ${SECONDS_WAITED} -le ${ROSETTA_MAX_WAIT_TIME_SECONDS} ] ; do
				sleep 1
				((SECONDS_WAITED=${SECONDS_WAITED}+1))
				ROSETTA_INSTALLED=`if ${PGREP} oahd >/dev/null 2>&1 ; then echo "YES"; else echo "NO" ; fi`
				if [ "${ROSETTA_INSTALLED}" == "YES" ] ; then
					EXIT_VALUE=0
					break
				fi
			done
			

		else
			EXIT_VALUE=0
		fi
	
	else
		EXIT_VALUE=0
	fi

else
	EXIT_VALUE=129
fi 

exit ${EXIT_VALUE}


